/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.ClientesDAO;
import Model.Clientes;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author casen
 */
public class frmClientes extends javax.swing.JFrame {

    /**
     * Creates new form frmClientes
     */
    //metodo listar
    public void Listar(){
        try {
                
            // Executar o select
            ClientesDAO dao = new ClientesDAO();
            List<Clientes> listadeclientes = dao.ListarClientes();
            
            //colocar os dados na tabela Jtable
            DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
            modelo.setNumRows(0);
            
            for(Clientes v: listadeclientes){
               modelo.addRow(new Object[]{
               v.getId(),
               v.getNome(),
               v.getCpf(),
               v.getTelefone(),
               v.getEmail(),
               v.getPlaca(),
               v.getServico()
            });
            }
            
        } catch (Exception e) {
        
        }
    }
    
    
    
    
    
    
    
    
    
    public frmClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        lblNome = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPlaca = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblCadastro = new javax.swing.JLabel();
        lblNovo = new javax.swing.JLabel();
        lblEditar = new javax.swing.JLabel();
        lblExcluir = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        lblidNaoEditavel = new javax.swing.JLabel();
        lblCanto = new javax.swing.JLabel();
        lblServico = new javax.swing.JLabel();
        txtServico = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Cpf", "Email", "Email", "Placa", "Servico"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabela);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 660, 350));

        lblNome.setText("Nome");
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 40, -1));

        lblCpf.setText("Cpf");
        getContentPane().add(lblCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        lblTelefone.setText("Telefone");
        getContentPane().add(lblTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        lblEmail.setText("Email");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, 20));

        lblPlaca.setText("Placa");
        getContentPane().add(lblPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        jLabel6.setText("Tabela de Clientes");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        lblCadastro.setText("Cadastrar Clientes ");
        getContentPane().add(lblCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, -1, -1));

        lblNovo.setText("Limpar Informações");
        getContentPane().add(lblNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, -1, -1));

        lblEditar.setText("Editar cadastros");
        getContentPane().add(lblEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, -1, -1));

        lblExcluir.setText("ExcluirCadastros");
        getContentPane().add(lblExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 410, -1, -1));

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 180, -1));

        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });
        getContentPane().add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 180, -1));

        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 180, -1));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 180, -1));

        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });
        getContentPane().add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 180, -1));

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 120, 40));

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 120, 40));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 120, 40));

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 430, 120, 40));

        txtCodigo.setEditable(false);
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 180, -1));

        lblCodigo.setText("ID");
        getContentPane().add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, 20));

        lblidNaoEditavel.setText("ID não Editavel");
        getContentPane().add(lblidNaoEditavel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        lblCanto.setText(" ");
        getContentPane().add(lblCanto, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 460, 40, -1));

        lblServico.setText("Servico");
        getContentPane().add(lblServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        txtServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServicoActionPerformed(evt);
            }
        });
        getContentPane().add(txtServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 180, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        try {
            //botão Cadastrar
            //guarda os dados da tela no obj
            Clientes obj= new Clientes();
            obj.setNome(txtNome.getText());
            obj.setCpf(txtCpf.getText());
            obj.setTelefone(txtTelefone.getText());
            obj.setEmail(txtEmail.getText());
            obj.setPlaca(txtPlaca.getText());
            obj.setServico(txtServico.getText());
            
            //Criar um objeto do tipo ClienteDAO

            ClientesDAO dao = new ClientesDAO();
            dao.cadastrarCliente(obj);
            
                        JOptionPane.showMessageDialog(null, "cadastro realizado com sucesso!");
        } catch (Exception erro) {
          JOptionPane.showMessageDialog(null, "erro ao cadastrar: " + erro);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
            //botao novo
            
           txtCodigo.setText(null);
           txtNome.setText(null);
           txtCpf.setText(null);
           txtTelefone.setText(null);
           txtEmail.setText(null);
           txtPlaca.setText(null);
           txtServico.setText(null);

    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // Botao editar
            try {
            Clientes obj = new Clientes();
            
            obj.setId(Integer.parseInt(txtCodigo.getText()));
            obj.setNome(txtNome.getText());
            obj.setCpf(txtCpf.getText());
            obj.setTelefone(txtTelefone.getText());
            obj.setEmail(txtEmail.getText());
            obj.setPlaca(txtPlaca.getText());
            obj.setServico(txtServico.getText());


            
            ClientesDAO dao = new ClientesDAO();
                    dao.alterarCliente(obj);
                        
            JOptionPane.showMessageDialog(null, "Alteração realizada com sucesso!");
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "erro ao alterar: " + erro);
        }
        
        
       
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // Botao Excluir
        try {
            Clientes obj = new Clientes();
            
            obj.setId(Integer.parseInt(txtCodigo.getText()));
            
            ClientesDAO dao = new ClientesDAO();
                    dao.excluirCliente(obj);
            
            JOptionPane.showMessageDialog(null, "Dados excluidos com sucesso!");            
        } catch (Exception erro) {
             JOptionPane.showMessageDialog(null, "Erro ao excluir: " + erro);
        }
        
        
        
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        //Listando dados na tabela
        Listar();
        
        
    }//GEN-LAST:event_formWindowActivated

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        //Coleta de dados de um Cliente
            txtCodigo.setText(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
            txtNome.setText(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());
            txtCpf.setText(tabela.getValueAt(tabela.getSelectedRow(), 2).toString());
            txtTelefone.setText(tabela.getValueAt(tabela.getSelectedRow(), 3).toString());
            txtEmail.setText(tabela.getValueAt(tabela.getSelectedRow(), 4).toString());
            txtPlaca.setText(tabela.getValueAt(tabela.getSelectedRow(), 5).toString());
            txtServico.setText(tabela.getValueAt(tabela.getSelectedRow(), 6).toString());
            
    }//GEN-LAST:event_tabelaMouseClicked

    private void txtServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCadastro;
    private javax.swing.JLabel lblCanto;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblExcluir;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNovo;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblServico;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblidNaoEditavel;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtServico;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
